package RegularPractice;

/* 389. Find the Difference
* You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
* */

import java.util.Stack;

class FindDifference{
    public  char findTheDifference( String s, String t){
        // Bit Manipulation
        char Xor = 0;
        for (int i = 0; i < s.length(); i++){
            Xor ^= s.charAt(i);
        }

        for (int i = 0; i < t.length(); i++){
            Xor ^= t.charAt(i);
        }
        return Xor;
//
//        // Solution using stack
//        Stack<Character> stack = new Stack<>();
//        for (char ch : t.toCharArray()){
//            stack.push(ch);
//        }
//        for (char ch: s.toCharArray()){
//            stack.removeElement(ch);
//        }
//        return stack.pop();
    }
}


public class LeetCode389 {
    public static void main(String[] args) {
        FindDifference solution = new FindDifference();

        // Test cases
        String s1 = "abcd";
        String t1 = "abcde";
        System.out.println("Test case 1:");
        System.out.println("Input: s = \"" + s1 + "\", t = \"" + t1 + "\"");
        System.out.println("Output: " + solution.findTheDifference(s1, t1)); // Output: e

        String s2 = "";
        String t2 = "y";
        System.out.println("Test case 2:");
        System.out.println("Input: s = \"" + s2 + "\", t = \"" + t2 + "\"");
        System.out.println("Output: " + solution.findTheDifference(s2, t2)); // Output: y

        // Additional test cases can be added here
    }
}
